### ISSUE TITLE
Add calibration file in two formats to every download

### ISSUE THREAD

**Issue by mhidas** [aodn/acoustic-data-viewer#16]
We are already including the calibration file (in Matlab format) to each download. It is stored in a subdirectory called _extras_ for each deployment. However, the current code only grabs one file (with hard-coded filename) from that subdirectory. We now have the calibration data in two formats (Matlab and CSV), and may want to include other relevant files in the future.

To make the process more flexible, could we modify the code so that it adds every file in the _extras_ subdirectory into every download?

**Comment by pblain** [comment]
Added to backlog
