### ISSUE TITLE
Preview images not displayed

### ISSUE THREAD

**Issue by mhidas** [aodn/acoustic-data-viewer#18]
Sasha Gavrilov (Curtin) reports that the viewer isn't fully working for him in Firefox (v33). Once he's selected a deployment, the long-term spectrogram is displayed and can be scrolled, but "doesn't respond to clicking at the selected time". What should happen is preview images of the selected recording should appear below the long-term spectrogram.

I've been unable to reproduce this under Linux or Windows (does the OS make a difference??). It works perfectly fine for me. Are there any settings within Firefox that might affect the behaviour?

**Comment by pmbohm** [comment]
@mhidas to fix the baseUrl in the ADV database

**Comment by mhidas** [comment]
all baseURLs changed to https
