### ISSUE TITLE
Update link to Matlab reader code

### ISSUE THREAD

**Issue by mhidas** [aodn/acoustic-data-viewer#25]
The migration to S3 has broken this link. Clicking the `Matlab data reader` button on the viewer gives a "404 Not Found" message, looking for key `IMOS/public/ANMN/Acoustic/code/index.html`. The new location is `IMOS/ANMN/Acoustic/code`.

Actually, now that the data-services repo is open, we could link to it directly:
https://raw.githubusercontent.com/aodn/data-services/master/ANMN/acoustic/NL_load_logger_data_new.m

**Comment by pmbohm** [comment]
@mhidas The new code is deployed now. It was a manual deployment using the war file from the Jenkins build.  No daily chef deploy for this machine it seems?

**Comment by mhidas** [comment]
@pmbohm Thanks.
