### ISSUE TITLE
Intermittent failure to display preview images

### ISSUE THREAD

**Issue by mhidas** [aodn/acoustic-data-viewer#30]
Sasha reports that 

> Recently I checked how the online acoustic data viewers was working  and found that ... mouse clicks at the long-term spectrogram (top panel) often didn’t bring or update the bottom panels, although the “adjust time” buttons worked well. This took place in both IE and Firefox. I couldn’t notice any regularity of when and why this happened.
> ...
> Can it be due to the time needed for the data server to localize the corresponding PNG files in the dataset, which is too long?

I have not been able to reproduce this issue myself (in Firefox 48.0). I asked him whether this was specific to any particular data set or time period, but...

> I cannot find any regularity of the viewer working well or failing to display the bottom panels.  This may happen with any dataset. Sometimes it opens the bottom panel after the first mouse click but then fails to update them at the following clips. Sometimes updating the upper panel (or changing the dataset) revives this functionality but only for a few clicks

**Comment by mhidas** [comment]
@pblain This is a new bug.

**Comment by pmbohm** [comment]
@mhidas I cant reproduce either, using Chrome. Is it worth asking Sacha if he can reproduce at this time?
